linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - exportloopref
  - gofmt
  - gofumpt
  - goimports
  - gosec
  - gosimple
  - govet
  - importas
  - megacheck
  - misspell
  - nakedret
  - nolintlint
  - revive
  - unconvert
  - unparam
  - wastedassign
